/**
 * Write .generated/embedded-fonts.css: one @font-face per Standard-edition font
 * (fonts/standard/*, vendored and hash-checked against fonts/manifest.json),
 * embedded as a data: URL. Coverage fonts get a unicode-range limited to the
 * visible assigned code points they map, so they never shadow a device font for
 * anything else; the placeholder and detection fonts cover everything and are
 * applied per cell. Runs before `vite build`; src/style.css imports the output.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { fontById, readFontManifest, type FontEntry } from "./fontManifest.js";
import { readCmap } from "./readCmap.js";
import { sha256Hex } from "./sha256Hex.js";
import { toUnicodeRange } from "./toUnicodeRange.js";
import { visibleAssignedSet } from "./visibleAssignedSet.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function readVendored(font: FontEntry): Uint8Array {
  if (!font.vendored) throw new Error(`${font.id} is in the standard edition but has no vendored file`);
  const bytes = new Uint8Array(readFileSync(resolve(repoRoot, font.vendored)));
  const sha = sha256Hex(bytes);
  if (sha !== font.woff2_sha256) throw new Error(`${font.vendored}: sha256 ${sha} does not match manifest ${font.woff2_sha256}`);
  return bytes;
}

function fontFace(font: FontEntry, bytes: Uint8Array, visible: ReadonlySet<number>): string {
  const format = font.vendored!.endsWith(".woff") ? "woff" : "woff2";
  const range = font.role === "coverage" ? `unicode-range:${toUnicodeRange(readCmap(bytes).filter((cp) => visible.has(cp)))};` : "";
  const data = Buffer.from(bytes).toString("base64");
  return `@font-face{font-family:"${font.css_family}";font-display:block;${range}src:url(data:font/${format};base64,${data}) format("${format}")}`;
}

/** The app needs only the Standard edition's fonts, not the whole manifest (which lists every pack font). */
function embeddedFontsTable(manifest: ReturnType<typeof readFontManifest>, standard: { fonts: string[]; guaranteed_visible_code_points?: number; of?: number }): void {
  const keep = ["id", "family", "css_family", "version", "license", "license_url", "role", "design", "assigned_visible_cmap_count"] as const;
  const fonts = standard.fonts.map((id) => fontById(manifest, id)).map((f) => Object.fromEntries(keep.filter((k) => f[k] !== undefined).map((k) => [k, f[k]])));
  const table = { _doc: "Generated by tools/fonts/embeddedFontsCss.ts from fonts/manifest.json (standard edition) — do not edit.", guaranteed: standard.guaranteed_visible_code_points ?? 0, of: standard.of ?? 0, fonts };
  writeFileSync(resolve(repoRoot, "src/data/embedded-fonts.json"), JSON.stringify(table, null, 1) + "\n");
}

export function embeddedFontsCss(): { fonts: number; bytes: number } {
  const manifest = readFontManifest(repoRoot);
  const standard = manifest.editions.find((e) => e.id === "standard");
  if (!standard) throw new Error("fonts/manifest.json has no standard edition");
  const visible = visibleAssignedSet(repoRoot);
  const faces = standard.fonts.map((id) => fontById(manifest, id)).map((font) => fontFace(font, readVendored(font), visible));
  const css = `/* generated by tools/fonts/embeddedFontsCss.ts — do not edit */\n${faces.join("\n")}\n`;
  mkdirSync(resolve(repoRoot, ".generated"), { recursive: true });
  writeFileSync(resolve(repoRoot, ".generated/embedded-fonts.css"), css);
  embeddedFontsTable(manifest, standard);
  return { fonts: faces.length, bytes: css.length };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const r = embeddedFontsCss();
  console.log(`generate:fonts-css — ${r.fonts} @font-face rules, ${r.bytes} bytes → .generated/embedded-fonts.css`);
}
