export interface DeviceFontCssInput { app: string; families: readonly string[]; verified: number; total: number; done: boolean; generic: string }

const quote = (f: string) => (/^[a-z-]+$/.test(f) ? f : `"${f.replace(/"/g, "")}"`);

/** The no-download form: installed fonts that served the selection on this device, labelled as device-specific (Q-13). */
export function deviceFontCss(i: DeviceFontCssInput): string {
  const share = i.total ? ((i.verified / i.total) * 100).toFixed(1) : "0.0";
  const count = i.done ? `${i.verified.toLocaleString("en-US")} of ${i.total.toLocaleString("en-US")} visible characters (${share}%)` : "counting\u2026";
  return [
    `/* Generated by Unicode Explorer ${i.app}: fonts already installed on THIS device that render characters in the selection.`,
    ` * Rendered here by these fonts: ${count}. Other systems have different fonts; use the web-font form for predictable results. */`,
    `.unicode-text {\n  font-family: ${[...i.families.map(quote), i.generic].join(", ")};\n}`,
    "",
  ].join("\n");
}
