import type { Span } from "./blockSpansFor.js";
import type { WebFontChoice } from "./chooseWebFonts.js";

export interface WebFontFace { family: string; face: string; weight: number; style: string; url: string; format: string; bytes: number; license: string; license_url: string }
export interface WebFontCssInput { app: string; blocks: readonly string[]; choice: WebFontChoice; faces: readonly WebFontFace[]; spans: Readonly<Record<string, readonly Span[]>>; generic: string }

const hex = (cp: number) => cp.toString(16).toUpperCase().padStart(4, "0");
const mb = (bytes: number) => `${(bytes / 1048576).toFixed(1)} MB`;
const pct = (a: number, b: number) => (b ? ((a / b) * 100).toFixed(1) : "0.0");
const quote = (family: string) => `"${family.replace(/"/g, "")}"`;

function header(i: WebFontCssInput, faces: readonly WebFontFace[]): string[] {
  const regular = faces.filter((f) => f.face === "Regular").reduce((s, f) => s + f.bytes, 0);
  const all = faces.reduce((s, f) => s + f.bytes, 0);
  const shown = i.blocks.length > 6 ? `${i.blocks.slice(0, 6).join(", ")} and ${i.blocks.length - 6} more` : i.blocks.join(", ");
  const licences = [...new Map(faces.map((f) => [f.family, `${f.family}: ${f.license} <${f.license_url}>`])).values()];
  return [
    `/* Generated by Unicode Explorer ${i.app} for ${i.blocks.length} block${i.blocks.length === 1 ? "" : "s"}: ${shown}.`,
    ` * Covers ${i.choice.covered.toLocaleString("en-US")} of ${i.choice.total.toLocaleString("en-US")} visible characters (${pct(i.choice.covered, i.choice.total)}%) with ${i.choice.chosen.length} web font famil${i.choice.chosen.length === 1 ? "y" : "ies"}.`,
    ` * File size, before any HTTP compression: ${mb(regular)} for the regular faces, ${mb(all)} with bold and italic; each file loads only when its unicode-range is used.`,
    " * URLs are pinned public copies recorded by the Unicode Font Kit (CORS-enabled). Check each licence before shipping:",
    ...licences.map((l) => ` *   ${l}`),
    " */",
  ];
}

function fontFace(f: WebFontFace, spans: readonly Span[]): string {
  const range = spans.map((s) => (s.start === s.end ? `U+${hex(s.start)}` : `U+${hex(s.start)}-${hex(s.end)}`)).join(", ");
  return `@font-face {\n  font-family: ${quote(f.family)};\n  src: url("${f.url}") format("${f.format}");\n  font-weight: ${f.weight};\n  font-style: ${f.style};\n  font-display: swap;\n  unicode-range: ${range};\n}`;
}

/** CSS another programmer can paste into their own page for the same coverage (Q-13). Text only. */
export function webFontCss(i: WebFontCssInput): string {
  const families = i.choice.chosen.map((c) => c.family);
  const faces = i.faces.filter((f) => families.includes(f.family)).sort((a, b) => families.indexOf(a.family) - families.indexOf(b.family));
  const rules = faces.map((f) => fontFace(f, i.spans[f.family] ?? []));
  const stack = `.unicode-text {\n  font-family: ${[...families.map(quote), i.generic].join(", ")};\n}`;
  return [...header(i, faces), "", ...rules, "", stack, ""].join("\n");
}
